// Generated by CoffeeScript 1.7.1
'use strict';
describe('Match Tree Builder', function() {
  describe('Add node', function() {
    var ptor = protractor.getInstance();
    beforeEach(function() {
      browser.get('app/index.html');
    });
    it('should have a tree with add button', function() {
      expect(element(By.css('.rootNode li:nth-child(0) .addButton'))).not.toBe(null);
    });
    return it('building a tree with add should result in an expected result', function() {
      element(By.css('.rootNode > .addButton')).click();
      element(By.css('.rootNode .treeNode > .addButton')).click();
      element(By.css('.rootNode .treeNode > .addButton')).click();
      ptor.debugger();
      expect(element.all(By.css('.rootNode .treeNode .treeNode')).count()).toEqual(2);
      expect(element.all(By.css('.rootNode .treeNode')).count()).toEqual(3);
    });
  });
});
