//Generated by CoffeeScript 1.7.1
var MatchTreeFilters;

MatchTreeFilters = angular.module('MatchTreeFilters', []);

MatchTreeFilters.filter('nodesummary', function() {
	console.log('Registering filter nodesummary');

	return function(inputNode) {
		switch (inputNode.type) {
		case 'MatchLocation' :
			var res = "Location " + inputNode.contig;
			res += "[";
			res += inputNode.start?inputNode.start:'*';
			res += "-";
			res += inputNode.end?inputNode.end:'*';
			res += "]";
			switch (inputNode.strand) {
			case 'true':
				res += '(+)';
				break;
			case 'false':
				res += '(-)';
				break;
			}
			return res; 
		default:
			return inputNode.type + " " + inputNode.name;

		}
	};
});

MatchTreeFilters.filter('detailurl', function() {
	console.log('Registering filter detailurl');

	return function(inputNode) {
		return "partial/node_detail_" + inputNode.type + ".html";
	};
});
