// Generated by CoffeeScript 1.7.1
'use strict';
describe('MatchTree controllers', function() {
  beforeEach(module('MatchTreeControllers'));
  return describe('TreeController', function() {
    var main;
    main = {};
    beforeEach(inject(function($rootScope, $controller) {
      main.scope = $rootScope.$new;
      return main.ctrl = $controller('TreeController', {
        $scope: main.scope
      });
    }));
    it('Should create initial tree', function() {
      return expect(main.scope.tree[0].name).toBe('Node');
    });
    return it('Initial root node should have initial focus', function() {
      return expect(main.scope.mainData.activeNode.name).toBe('Node');
    });
  });
});
